version: '3.1'

volumes:
  nextcloud:
  cloud_db:

networks:
  web:
    external: true
  back:
    driver: bridge
  
services:
  cloud_db:
    image: mariadb
    restart: always
    volumes:
      - cloud_db:/var/lib/mysql
    networks:
      - back
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXXXXXXXXXXXXXX
      - MYSQL_PASSWORD=XXXXXXXXXXXXXXXXXXXXX
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_OVERWRITEPROTOCOL=https
        #labels:
            #     - "traefik.enable=false"
  cloud_app:
    image: nextcloud:22.2.5-apache
    links:
      - cloud_db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    networks:
      - web
      - back
    depends_on:
      - cloud_db
    labels:
      - "traefik.frontend.rule=Host:cloud.example.de"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.backend=nextcloud"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.STSSeconds=15552000"
      - "traefik.frontend.redirect.permanent=true"
      - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
