version: "2"

networks:
  web:
    external: true
    
services:
  grafana:
    image: grafana/grafana:5.1.0
    user: "104"
    networks:
      - web
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=XXXXXXXXXXXXX
    labels:
      - "traefik.frontend.rule=Host:stats.example.de"
      - "traefik.port=3000"
      - "traefik.backend=grafana"
      - "traefik.frontend.entryPoints=https"
      - "traefik.docker.network=web"
