version: '3.3'

networks:
  web:
    external: true
  back:
    driver: bridge

services:
   db:
     networks: 
       - back
     image: mysql:5.7
     volumes:
       - weh_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: XXXXXXXXXXXXX
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: XXXXXXXXXXXXXXXXXX

   wordpress:
     depends_on:
       - db
     networks:
       - web
       - back
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: XXXXXXXXXXXX
       WORDPRESS_DB_NAME: wordpress
     labels:
      - "traefik.frontend.rule=Host:web.example.de"
      - "traefik.port=80"
      - "traefik.backend=wordpress"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=web"
      - "traefik.frontend.redirect.permanent=true"

volumes:
    weh_db_data: {}
